# Generated by Django 6.0 on 2025-12-18 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='opt',
            new_name='otp',
        ),
    ]
